[package]
name = "p2p-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4" }
env_logger = { version = "0.11" }
rustls = { version = "0.23" }
rustls-platform-verifier = { version = "0.6" }
rustls-openssl = { version = "0.3" }
